name: test-on-push
on: [push]
jobs:
    checkfixup:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - run: make checkfixup

    lint:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - run: make setup
            - run: make lint

    typecheck:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - run: make setup
            - run: make typecheck

    checkformatting:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - run: make setup
            - run: make checkformatting

    test:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - run: make setup
            - run: make test

    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            - run: make setup
            - run: make build
